### ISSUE TITLE
Upgrade to Boot 1.5.1, SF 4.3.6 and SI 4.3.7 releases

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/app-starters-release#57]
As a developer, I'd like to upgrade SF to 4.3.6 and SI to 4.3.7 releases. 

**Acceptance:**
All apps include the latest SF and SI releases as the core dependency

**Comment by artembilan** [comment]
@sabbyanandan ,

since Spring Boot `1.5.0` is out, let's figure out if we need stay with Boot `1.4.x` yet.

Anyway looks like we should wait for proper `spring-cloud-build` version to upgrade everything in one `core` place.

Right, some individual apps, like `mail` should be revisited for their custom versions during the work of this issue...

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud-stream-app-starters/core/commit/136aa49fbe27797007e0d1fe7b6254580aa73152.
